<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>purs</string>
		<string>purs.hs</string>
	</array>
	<key>name</key>
	<string>PureScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*\b(module)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(where)\b</string>
			<key>name</key>
			<string>meta.section.module.purescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module-name</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(import)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.declaration.import.purescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module-name</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\b(type)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.declaration.type.purescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-simple</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\b(class)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(where)\b|$</string>
			<key>name</key>
			<string>meta.declaration.typeclass.purescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([A-Z][\w.']*)</string>
					<key>name</key>
					<string>entity.other.inherited-class.purescript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-typeclass</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic-tyvar</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\b(instance)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(where)\b|$</string>
			<key>name</key>
			<string>meta.declaration.instance.purescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-signature</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\w+|\(.+\))\s*(::)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.purescript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.has-type.purescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.declaration.function.purescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-signature</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ffi.purescript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(foreign)\s+(import)\s+(data)\s+(.+?)\s+(::)</string>
			<key>name</key>
			<string>meta.declaration.ffi.data.purescript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(foreign)\s+(import)\s+(.+?)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ffi.purescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(::)(.+?)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>substringkeyword.operator.purescript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.ffi.function.purescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ffi</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reserveds</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#prelude</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#array</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#eff</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#either</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#error</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#global</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ioref</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#math</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#maybe</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#monad</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#monoid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#random</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#regex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#st</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#trace</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tuple</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#data</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#array-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-op</string>
				</dict>
			</array>
		</dict>
		<key>array-function</key>
		<dict>
			<key>match</key>
			<string>\b(all|any|concat|concatMap|deleteAt|filter|find|foldl|foldr|head|indexOf|insertAt|isEmpty|joinS|joinWith|lastIndexOf|length|map|push|range|reverse|shift|singleton|slice|sort|tail|updateAt|zipWith)\b</string>
			<key>name</key>
			<string>support.function.array.purescript</string>
		</dict>
		<key>array-op</key>
		<dict>
			<key>match</key>
			<string>(:)</string>
			<key>name</key>
			<string>support.op.array.purescript</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\-\-.*</string>
					<key>name</key>
					<string>comment.line.purescript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{\-</string>
					<key>end</key>
					<string>\-\}</string>
					<key>name</key>
					<string>comment.block.purescript</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.purescript</string>
		</dict>
		<key>data</key>
		<dict>
			<key>match</key>
			<string>\b([A-Z]\w*)\b</string>
			<key>name</key>
			<string>constant.other.purescript</string>
		</dict>
		<key>decl-ctor</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.purescript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.purescript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*([A-Z][\w\.]*?)\s+([A-Z][\w\.]*)\s*</string>
		</dict>
		<key>eff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#eff-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#eff-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#eff-type</string>
				</dict>
			</array>
		</dict>
		<key>eff-data</key>
		<dict>
			<key>match</key>
			<string>\b(Eff)\b</string>
			<key>name</key>
			<string>support.function.data.eff.purescript</string>
		</dict>
		<key>eff-function</key>
		<dict>
			<key>match</key>
			<string>\b(bindEff|forE|foreachE|retEff|runPure|untilE|whileE)\b</string>
			<key>name</key>
			<string>support.function.eff.purescript</string>
		</dict>
		<key>eff-type</key>
		<dict>
			<key>match</key>
			<string>\b(Pure)\b</string>
			<key>name</key>
			<string>support.type.eff.purescript</string>
		</dict>
		<key>either</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#either-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#either-function</string>
				</dict>
			</array>
		</dict>
		<key>either-data</key>
		<dict>
			<key>match</key>
			<string>\b(Left|Right)\b</string>
			<key>name</key>
			<string>support.function.data.either.purescript</string>
		</dict>
		<key>either-function</key>
		<dict>
			<key>match</key>
			<string>\b(either)\b</string>
			<key>name</key>
			<string>support.function.either.purescript</string>
		</dict>
		<key>enum</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#enum-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum-typeclass</string>
				</dict>
			</array>
		</dict>
		<key>enum-function</key>
		<dict>
			<key>match</key>
			<string>\b(fromEnum|toEnum)\b</string>
			<key>name</key>
			<string>support.function.enum.purescript</string>
		</dict>
		<key>enum-typeclass</key>
		<dict>
			<key>match</key>
			<string>\b(Enum)\b</string>
			<key>name</key>
			<string>storage.type.enum.purescript</string>
		</dict>
		<key>error</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#error-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#error-function</string>
				</dict>
			</array>
		</dict>
		<key>error-data</key>
		<dict>
			<key>match</key>
			<string>\b(Error)\b</string>
			<key>name</key>
			<string>support.function.data.error.purescript</string>
		</dict>
		<key>error-function</key>
		<dict>
			<key>match</key>
			<string>\b(catchError|throwError)\b</string>
			<key>name</key>
			<string>support.function.error.purescript</string>
		</dict>
		<key>ffi</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>generic-tyvar</key>
		<dict>
			<key>match</key>
			<string>\b([a-z][\w']*)\b</string>
			<key>name</key>
			<string>variable.other.purescript</string>
		</dict>
		<key>global</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#global-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#global-function</string>
				</dict>
			</array>
		</dict>
		<key>global-constant</key>
		<dict>
			<key>match</key>
			<string>\b(infinity|nan)\b</string>
			<key>name</key>
			<string>constant.support.global.purescript</string>
		</dict>
		<key>global-function</key>
		<dict>
			<key>match</key>
			<string>\b(decodeURI|decodeURIComponent|encodeURI|encodeURIComponent|isFinite|isNaN|parseFloat|parseInt|toExponential|toFixed|toPrecision)\b</string>
			<key>name</key>
			<string>support.function.global.purescript</string>
		</dict>
		<key>ioref</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ioref-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ioref-function</string>
				</dict>
			</array>
		</dict>
		<key>ioref-data</key>
		<dict>
			<key>match</key>
			<string>\b(IORef|Ref)\b</string>
			<key>name</key>
			<string>support.function.data.ioref.purescript</string>
		</dict>
		<key>ioref-function</key>
		<dict>
			<key>match</key>
			<string>\b(modifyIORef|newIORef|readIORef|unsafeRunIORef|writeIORef)\b</string>
			<key>name</key>
			<string>support.function.ioref.purescript</string>
		</dict>
		<key>math</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#math-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#math-function</string>
				</dict>
			</array>
		</dict>
		<key>math-constant</key>
		<dict>
			<key>match</key>
			<string>\b(e|ln10|ln2|log10e|log2e|pi|sqrt1_2|sqrt2)\b</string>
			<key>name</key>
			<string>constant.support.math.purescript</string>
		</dict>
		<key>math-function</key>
		<dict>
			<key>match</key>
			<string>\b(abs|aceil|acos|asin|atan|atan2|cos|exp|floor|log|max|min|pow|round|sin|sqrt|tan)\b</string>
			<key>name</key>
			<string>support.function.math.purescript</string>
		</dict>
		<key>maybe</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#maybe-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#maybe-function</string>
				</dict>
			</array>
		</dict>
		<key>maybe-data</key>
		<dict>
			<key>match</key>
			<string>\b(Just|Nothing)\b</string>
			<key>name</key>
			<string>support.function.data.maybe.purescript</string>
		</dict>
		<key>maybe-function</key>
		<dict>
			<key>match</key>
			<string>\b(maybe|fromMaybe)\b</string>
			<key>name</key>
			<string>support.function.maybe.purescript</string>
		</dict>
		<key>module-name</key>
		<dict>
			<key>match</key>
			<string>([A-Za-z][\w\.']*)</string>
			<key>name</key>
			<string>support.other.module.purescript</string>
		</dict>
		<key>monad</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#monad-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#monad-op</string>
				</dict>
			</array>
		</dict>
		<key>monad-function</key>
		<dict>
			<key>match</key>
			<string>\b(replicateM|mapM|sequence|join|foldM|when)\b</string>
			<key>name</key>
			<string>support.function.monad.purescript</string>
		</dict>
		<key>monad-op</key>
		<dict>
			<key>match</key>
			<string>(&gt;=&gt;|&lt;=&lt;)</string>
			<key>name</key>
			<string>support.op.monad.purescript</string>
		</dict>
		<key>monoid</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#monoid-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#monoid-op</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#monoid-typeclass</string>
				</dict>
			</array>
		</dict>
		<key>monoid-function</key>
		<dict>
			<key>match</key>
			<string>\b(mconcat|mempty)\b</string>
			<key>name</key>
			<string>support.function.monoid.purescript</string>
		</dict>
		<key>monoid-op</key>
		<dict>
			<key>match</key>
			<string>(&lt;&gt;)</string>
			<key>name</key>
			<string>support.op.monoid.purescript</string>
		</dict>
		<key>monoid-typeclass</key>
		<dict>
			<key>match</key>
			<string>\b(Monoid)\b</string>
			<key>name</key>
			<string>storage.type.monoid.purescript</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w)(\b(\d+)|(\d+(\.\d+)?(e[+-]?\d+)?)\b)</string>
			<key>name</key>
			<string>constant.numeric.purescript</string>
		</dict>
		<key>prelude</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#prelude-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-typeclass</string>
				</dict>
			</array>
		</dict>
		<key>prelude-data</key>
		<dict>
			<key>match</key>
			<string>\b(Ref)\b</string>
			<key>name</key>
			<string>support.function.data.prelude.purescript</string>
		</dict>
		<key>prelude-function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(const|flip)\b</string>
					<key>name</key>
					<string>support.function.prelude.purescript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-alternative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-applicative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-bits</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-boollike</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-category</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-monad</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-num</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-ord</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-read</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-function-show</string>
				</dict>
			</array>
		</dict>
		<key>prelude-function-alternative</key>
		<dict>
			<key>match</key>
			<string>\b(empty)\b</string>
			<key>name</key>
			<string>support.function.prelude.alternative.purescript</string>
		</dict>
		<key>prelude-function-applicative</key>
		<dict>
			<key>match</key>
			<string>\b(pure)\b</string>
			<key>name</key>
			<string>support.function.prelude.applicative.purescript</string>
		</dict>
		<key>prelude-function-bits</key>
		<dict>
			<key>match</key>
			<string>\b(complement|shl|shr|numAnd|numComplement|numOr|numShl|numShr|numXor|numZshr|zshr)\b</string>
			<key>name</key>
			<string>support.function.prelude.bits.purescript</string>
		</dict>
		<key>prelude-function-boollike</key>
		<dict>
			<key>match</key>
			<string>\b(boolAnd|boolNot|boolOr|not)\b</string>
			<key>name</key>
			<string>support.function.prelude.boollike.purescript</string>
		</dict>
		<key>prelude-function-category</key>
		<dict>
			<key>match</key>
			<string>\b(id)\b</string>
			<key>name</key>
			<string>support.function.prelude.category.purescript</string>
		</dict>
		<key>prelude-function-monad</key>
		<dict>
			<key>match</key>
			<string>\b(return)\b</string>
			<key>name</key>
			<string>support.function.prelude.monad.purescript</string>
		</dict>
		<key>prelude-function-num</key>
		<dict>
			<key>match</key>
			<string>\b(negate|numAdd|numDiv|numMod|numMul|numNegate|numSub)\b</string>
			<key>name</key>
			<string>support.function.prelude.num.purescript</string>
		</dict>
		<key>prelude-function-ord</key>
		<dict>
			<key>match</key>
			<string>\b(numLess|numLessEq|numGreater|numGreaterEq)\b</string>
			<key>name</key>
			<string>support.function.prelude.ord.purescript</string>
		</dict>
		<key>prelude-function-read</key>
		<dict>
			<key>match</key>
			<string>\b(read|readNumber)\b</string>
			<key>name</key>
			<string>support.function.prelude.read.purescript</string>
		</dict>
		<key>prelude-function-ref</key>
		<dict>
			<key>match</key>
			<string>\b(liftRef|refEq|refIneq|unsafeRefEq|unsafeRefIneq)\b</string>
			<key>name</key>
			<string>support.function.prelude.ref.purescript</string>
		</dict>
		<key>prelude-function-show</key>
		<dict>
			<key>match</key>
			<string>\b(show|showNumber)\b</string>
			<key>name</key>
			<string>support.function.prelude.show.purescript</string>
		</dict>
		<key>prelude-op</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$|#)</string>
					<key>name</key>
					<string>support.type.op.prelude.purescript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-alternative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-applicative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-bits</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-boollike</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-category</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-eq</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-functor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-monad</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-num</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prelude-op-ord</string>
				</dict>
			</array>
		</dict>
		<key>prelude-op-alternative</key>
		<dict>
			<key>match</key>
			<string>(&lt;\|&gt;)</string>
			<key>name</key>
			<string>support.type.op.prelude.alternative.purescript</string>
		</dict>
		<key>prelude-op-applicative</key>
		<dict>
			<key>match</key>
			<string>(&lt;\*&gt;)</string>
			<key>name</key>
			<string>support.type.op.prelude.applicative.purescript</string>
		</dict>
		<key>prelude-op-bits</key>
		<dict>
			<key>match</key>
			<string>(&amp;|\||\^)</string>
			<key>name</key>
			<string>support.type.op.prelude.bits.purescript</string>
		</dict>
		<key>prelude-op-boollike</key>
		<dict>
			<key>match</key>
			<string>(&amp;&amp;|\|\||\^)</string>
			<key>name</key>
			<string>support.type.op.prelude.boollike.purescript</string>
		</dict>
		<key>prelude-op-category</key>
		<dict>
			<key>match</key>
			<string>(&lt;&lt;&lt;|&gt;&gt;&gt;)</string>
			<key>name</key>
			<string>support.type.op.prelude.category.purescript</string>
		</dict>
		<key>prelude-op-eq</key>
		<dict>
			<key>match</key>
			<string>(==|/=)</string>
			<key>name</key>
			<string>support.type.op.prelude.eq.purescript</string>
		</dict>
		<key>prelude-op-functor</key>
		<dict>
			<key>match</key>
			<string>(&lt;\$&gt;)</string>
			<key>name</key>
			<string>support.type.op.prelude.functor.purescript</string>
		</dict>
		<key>prelude-op-monad</key>
		<dict>
			<key>match</key>
			<string>(&gt;&gt;=)</string>
			<key>name</key>
			<string>support.type.op.prelude.monad.purescript</string>
		</dict>
		<key>prelude-op-num</key>
		<dict>
			<key>match</key>
			<string>(\+|\-|\*|/|%)</string>
			<key>name</key>
			<string>support.type.op.prelude.num.purescript</string>
		</dict>
		<key>prelude-op-ord</key>
		<dict>
			<key>match</key>
			<string>(&lt;|&lt;=|&gt;|&gt;=)</string>
			<key>name</key>
			<string>support.type.op.prelude.ord.purescript</string>
		</dict>
		<key>prelude-type</key>
		<dict>
			<key>match</key>
			<string>\b(Boolean|Number|String)\b</string>
			<key>name</key>
			<string>support.type.prelude.purescript</string>
		</dict>
		<key>prelude-typeclass</key>
		<dict>
			<key>match</key>
			<string>\b(Alternative|Applicative|Bits|BoolLike|Category|Eq|Functor|Monad|Num|Ord|Read|Show)\b</string>
			<key>name</key>
			<string>storage.type.prelude.purescript</string>
		</dict>
		<key>random</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#random-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#random-function</string>
				</dict>
			</array>
		</dict>
		<key>random-data</key>
		<dict>
			<key>match</key>
			<string>\b(Random)\b</string>
			<key>name</key>
			<string>support.function.data.random.purescript</string>
		</dict>
		<key>random-function</key>
		<dict>
			<key>match</key>
			<string>\b(random)\b</string>
			<key>name</key>
			<string>support.function.random.purescript</string>
		</dict>
		<key>regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#regex-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex-function</string>
				</dict>
			</array>
		</dict>
		<key>regex-data</key>
		<dict>
			<key>match</key>
			<string>\b(Regex)\b</string>
			<key>name</key>
			<string>support.function.data.regex.purescript</string>
		</dict>
		<key>regex-function</key>
		<dict>
			<key>match</key>
			<string>\b(match|regex|replaceR|search|test)\b</string>
			<key>name</key>
			<string>support.function.regex.purescript</string>
		</dict>
		<key>reserveds</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#reserveds-control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reserveds-other</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reserveds-operator</string>
				</dict>
			</array>
		</dict>
		<key>reserveds-control</key>
		<dict>
			<key>match</key>
			<string>\b(case|do|else|if|in|let|of|then)\b</string>
			<key>name</key>
			<string>keyword.control.purescript</string>
		</dict>
		<key>reserveds-operator</key>
		<dict>
			<key>match</key>
			<string>=&gt;|\-&gt;|=|\.|\\</string>
			<key>name</key>
			<string>keyword.operator.purescript</string>
		</dict>
		<key>reserveds-other</key>
		<dict>
			<key>match</key>
			<string>\b(as|class|data|forall|foreign|import|infix|infixl|infixr|instance|module|newtype|qualified|type|where)\b</string>
			<key>name</key>
			<string>keyword.other.purescript</string>
		</dict>
		<key>st</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#st-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#st-function</string>
				</dict>
			</array>
		</dict>
		<key>st-data</key>
		<dict>
			<key>match</key>
			<string>\b(ST|STRef|STArray)\b</string>
			<key>name</key>
			<string>support.function.data.st.purescript</string>
		</dict>
		<key>st-function</key>
		<dict>
			<key>match</key>
			<string>\b(modifySTRef|newSTArray|newSTRef|peekSTArray|pokeSTArray|readSTRef|runST|runSTArray|writeSTRef)\b</string>
			<key>name</key>
			<string>support.function.st.purescript</string>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-function</string>
				</dict>
			</array>
		</dict>
		<key>string-function</key>
		<dict>
			<key>match</key>
			<string>\b(charAt|indexOfS|lastIndexOfS|lengthS|localeCompare|replace|sliceS|split|substr|substring|toLower|toUpper|trim)\b</string>
			<key>name</key>
			<string>support.function.string.purescript</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(')</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.string.purescript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')</string>
					<key>name</key>
					<string>invalid-strings</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>invalid.illegal.string.purescript</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\")</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.purescript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.purescript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.purescript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings-escapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings-escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\('|\"|\\|/|b|f|n|r|t|v|0|u[0-9a-fA-F]{4})</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<key>trace</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#trace-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#trace-function</string>
				</dict>
			</array>
		</dict>
		<key>trace-data</key>
		<dict>
			<key>match</key>
			<string>\b(Trace)\b</string>
			<key>name</key>
			<string>support.function.data.trace.purescript</string>
		</dict>
		<key>trace-function</key>
		<dict>
			<key>match</key>
			<string>\b(print|trace)\b</string>
			<key>name</key>
			<string>support.function.trace.purescript</string>
		</dict>
		<key>tuple</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tuple-function</string>
				</dict>
			</array>
		</dict>
		<key>tuple-function</key>
		<dict>
			<key>match</key>
			<string>\b(curry|uncurry|unzip|zip)\b</string>
			<key>name</key>
			<string>support.function.tuple.purescript</string>
		</dict>
		<key>type-constraint</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.purescript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.purescript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.purescript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.type.purescript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*([A-Z][\w.']*)\s+([A-Za-z][\w.']*)\s*(=&gt;)</string>
					<key>name</key>
					<string>meta.constraint.purescript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=.*=&gt;)\(</string>
					<key>end</key>
					<string>\)\s*(=&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.purescript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.constraint.purescript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.purescript</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.purescript</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*([A-Z][\w.']*)\s+([A-Za-z][\w.']*)\s*</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type-signature</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-simple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-constraint</string>
				</dict>
			</array>
		</dict>
		<key>type-simple</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.purescript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.purescript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\((-&gt;)\)|(-&gt;)</string>
					<key>name</key>
					<string>arrow.operator.purescript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Z][\w.']*)</string>
					<key>name</key>
					<string>storage.type.purescript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic-tyvar</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.purescript</string>
	<key>uuid</key>
	<string>a2569d0d-e592-4873-9488-e0b8d894ac3e</string>
</dict>
</plist>
